Proposed functional slice breakdown
cjdcordeiro/chisel-releases pull request #4
Opened 2023-05-15 21:56 UTC by vpa1977

Split slices into
- core : minimal set of files required for running java 8
- security: required for encryption and tls tasks
- devel: debugging, profiling and instrumentation
- awt: graphics tasks
- tools: tools laucher

This allows to build chiselled jre based on the functions required:

```
RUN mkdir -p /rootfs \
      && chisel cut --release /opt/chisel-releases --root /rootfs \
     openjdk-8-jre-headless_core  \
     openjdk-8-jre-headless_security  \
    base-files_bin \
```

will build something that can curl github over https.

```
RUN mkdir -p /rootfs \
      && chisel cut --release /opt/chisel-releases --root /rootfs \
     openjdk-8-jre-headless_core  \
     openjdk-8-jre-headless_security  \
     openjdk-8-jre-headless_management \
    base-files_bin \
```

host a minecraft server

```
RUN mkdir -p /rootfs \
      && chisel cut --release /opt/chisel-releases --root /rootfs \
     openjdk-8-jre-headless_core  \
     openjdk-8-jre-headless_security  \
     openjdk-8-jre-headless_awt \
    base-files_bin \
```
manipulate pdf files

etc.

2023-05-16 06:58 UTC, vpa1977 commented
- lets split devel slice into jfr / debugging|profiling
-  split out ext slice from core
-  comment on core that we should not take away dependencies since rt.jar is there
-

2023-05-17 12:41 UTC, cjdcordeiro requested changes
Thanks @vpa1977 ! This is looking great. I confirm that this is the right approach (slicing with basis on the functional unit).

I've left a few comments and suggestions for changes, but after that, we should be good to merge it ;)

2023-05-17 12:41 UTC, cjdcordeiro commented on slices/openjdk-8-jre-headless.yaml
> +      /usr/lib/jvm/java-8-openjdk-*/jre/lib/*/libnpt.so:
fyi, this is a PR aiming at solving the bug: https://github.com/canonical/chisel/pull/62

2023-05-17 12:41 UTC, cjdcordeiro commented on slices/openjdk-8-jre-headless.yaml
> +      - media-types_data
this is not a direct dependency of the DEB, so I'd drop it, and then we include it explicitly when running `chisel cut` for the chiselled-jre (which is what we are doing already)

2023-05-17 12:41 UTC, cjdcordeiro commented on slices/openjdk-8-jre-headless.yaml
>        /etc/java-8-openjdk/sound.properties:
I though you wanted to drop this? You've dropped the symlink `./usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sound.properties`, and we're not including `./usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjsound.so`, so I'm not sure if this is still relevant

2023-05-18 04:02 UTC, vpa1977 commented on slices/openjdk-8-jre-headless.yaml
>        /usr/lib/jvm/java-8-openjdk-*/jre/lib/security/java.policy:
yes, was in the wrong slice ;(

2023-05-18 04:10 UTC, vpa1977 commented on slices/openjdk-8-jre-headless.yaml
> +      /usr/lib/jvm/java-8-openjdk-*/jre/lib/*/libnpt.so:
Those are agents, so without explicitly adding them to the command line, they will not be loaded/running => so we are not increasing security risk profile but having those. The size is ~500 kb uncompressed, so lets just merge those slices for now.

2023-05-18 04:15 UTC, vpa1977 commented on slices/openjdk-8-jre-headless.yaml
> +      /etc/java-8-openjdk/security/java.policy:
java.policy is located under /security/ but in our case security slice is crypto and TLS and java.policy is a sandbox security file. It describes permissions for various classes and how they can interact with operating system. 
Hence it is in the core slice.

2023-05-18 04:18 UTC, vpa1977 commented
I've added draft https://github.com/ubuntu-rocks/chiselled-jre/pull/107 for the chiselled jre so that we could validate this pull request against chiselled jre repo

2023-05-19 16:19 UTC, cjdcordeiro commented on slices/openjdk-8-jre-headless.yaml
> +      /etc/java-8-openjdk/security/java.policy:
@vpa1977 why are these in `core`? they are again in `security`, which depends on core, so it sounds redundant unless `core` is supposed some minimal security features?

2023-05-19 16:21 UTC, cjdcordeiro commented on slices/openjdk-8-jre-headless.yaml
> +      /usr/lib/jvm/java-8-openjdk-*/jre/lib/*/libnpt.so:
it's better to split them still, and use the no2 approach above. I'll do that

2023-05-19 16:34 UTC, cjdcordeiro commented
thanks for this @vpa1977 

i'll merge it and do some changes.

2023-05-19 16:34 UTC, cjdcordeiro approved these changes

2023-05-19 16:34 UTC, cjdcordeiro approved these changes

2023-05-19 16:35 UTC, merged